### ISSUE TITLE
could not decrypt data: cipher: message authentication failed

### ISSUE THREAD

**Issue by hessijames79** [hazcod/enpass-cli#114]
Hi!

enpass-cli is mostly working fine for me. I'm using the current App Store version of Enpass (macOS 6.8.1 (1060)).

Unfortunately, some of the items fail to decrypt:
% enp -log debug show 'redacted'
DEBU[0000] checking provided vault paths
DEBU[0000] loading vault info
DEBU[0000] vault info loaded                             vault_name=Standard vault_version=6
DEBU[0000] initialized paths                             db_path=vault.enpassdb info_path=vault.json
DEBU[0000] PIN disabled
Enter master password:
DEBU[0003] generating database key
DEBU[0003] generating master password
DEBU[0003] not using keyfile
DEBU[0003] extracting salt from database
DEBU[0003] deriving decryption key
DEBU[0003] opening encrypted database
DEBU[0003] opened vault
ERRO[0004] could not decrypt redacted  error="could not decrypt data: cipher: message authentication failed"
DEBU[0004] closed vault                                  error="<nil>"

**Comment by msladek** [comment]
Hey @hessijames79

Sorry for the late reply. I've never encountered this issue with any vault entry and I cannot reproduce it. I assume the card opens fine in the GUI app?

Perhaps @hazcod has an idea since he has written the `Card.Decrypt()` function?

If you want me to debug your problem, it would be good if you could provide me a vault with a single card having this very issue. Just make sure there are no actual secrets of yours contained in the vault!

**Comment by hessijames79** [comment]
Hey!

> Sorry for the late reply. I've never encountered this issue with any vault entry and I cannot reproduce it. I assume the card opens fine in the GUI app?

Yes it does in Enpass Mac 6.8.2 (1082) Mac App Store

> If you want me to debug your problem, it would be good if you could provide me a vault with a single card having this very issue. Just make sure there are no actual secrets of yours contained in the vault!

To my surprise, it was quite easy. I didn't even have to move one of the problematic entries to a new vault. It was sufficient, to create a new credit card(!). I found out that items of type login and password work fine and all other types (credit card, identity, finance, license, travel and computer) trigger the error.

```
%tar -xzf testenpasscli.tgz;enpasscli -vault ./27e9a7e8-6fe7-471f-9f11-111e1072ca9a show
Enter master password:
ERRO[0002] could not decrypt card                        error="could not decrypt data: cipher: message authentication failed"
INFO[0002] > title: login  login: user  cat. : login  pass : password
ERRO[0002] could not decrypt identity                    error="could not decrypt data: cipher: message authentication failed"
INFO[0002] > title: password  login: test  cat. : password  pass : tets
ERRO[0002] could not decrypt finance                     error="could not decrypt data: cipher: message authentication failed"
ERRO[0002] could not decrypt license                     error="could not decrypt data: cipher: message authentication failed"
ERRO[0002] could not decrypt travel                      error="could not decrypt data: cipher: message authentication failed"
ERRO[0002] could not decrypt computer                    error="could not decrypt data: cipher: message authentication failed"
```

I attached the example vault. Password is 'secret'.

Patrick

[testenpasscli.tgz](https://github.com/hazcod/enpass-cli/files/9126729/testenpasscli.tgz)

**Comment by msladek** [comment]
Thanks for the vault, that helps a lot!

I analysed the situation and it fails to decrypt these items because there is no password value to decrypt. If `-type=TYPE` is ommited, which defaults to `-type=password`, only passwords are supposed be read from the vault. Yet every item regardless of its category seems to have a password field attached, even if the GUI doesn't show it. These password fields values are empty thus decryption fails.

To fix this error we could simply check if the value is non empty. I'll open a PR.

**Comment by msladek** [comment]
thanks for merging & releasing @hazcod

**Comment by msladek** [comment]
for displaying credit card numbers try `enpasscli -type=ccNumber show`

there are many credit card specific fields, here are most of them: `ccName`, `ccNumber`, `ccCvc`, `ccPin`, `ccExpiry`, `ccBankname`, `ccTxnpassword`, `ccType`

**Comment by hessijames79** [comment]
I must admit, that is the last thing I expected given the help text "The type of your card."

Thank you again for fixing the issue and the help.
