### ISSUE TITLE
Unknown driver "sqlite3" (forgotten import?)

### ISSUE THREAD

**Issue by erenfro** [hazcod/enpass-cli#93]
So, I just downloaded release 1.0.1 for linux-amd64, and after getting it to point properly to my vault path, of $HOME/Documents/Enpass/Vaults/primary, it gave me this error:

FATA[0003] could not open vault                          error="could not open v: could not open database: sql: unknown driver \"sqlite3\" (forgotten import?)"                                

BTW, really glad you came back to work on this. And it seems like golang might be the way to go with this. :+1:

**Comment by hazcod** [comment]
Hi @erenfro , I've pushed a potential fix in https://github.com/hazcod/enpass-cli/commit/609a285355cf8a4634b8212f9304cd9db1237d10.

The ci/cd pipeline still seems to be wonky, I'll look into that the following days.

**Comment by hazcod** [comment]
@erenfro can you try in the meantime while installing `libsqlite3-dev` ?

**Comment by Kwbmm** [comment]
Hello! Thanks for this incredible work!

I have bumped into the same issue as @erenfro . I'm running Manjaro, thus I didn't find any `libsqlite3-dev` package in the repos, however I already have [sqlite3](https://www.archlinux.org/packages/?name=sqlite) package installed

**Comment by hazcod** [comment]
Hmm, not sure how I can make cross-compilation work on GitHub Actions (or what packages are required).
Perhaps we could use a docker image to compile the Go app?

**Comment by Kwbmm** [comment]
Docker image would do the trick for sure. But it's more expensive..

I'm not acquainted with github actions, but I assumed that `runs-on` directive would have done the trick.

Maybe, setting cross-compile env vars (`GOOS` and `GOARCH`) may help?

Some references:

  - https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/
  - http://golangcookbook.com/chapters/running/cross-compiling/

**Comment by Kwbmm** [comment]
I'm not sure my findings are of any help BUT

Just for fun, I made a `golang:1.15-alpine` docker container, cloned this repo on my machine and mapped this repo's folder to a folder inside the container.

I went into the container and launched `go build` inside `cmd/enpasscli` folder. There I got an executable.

I then exited the container and tried to run the executable from my machine, but I was getting `zsh: no such file or directory: ./enpasscli`. Very strange.. 
I first run `file enpasscli`:

```
enpasscli: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, Go BuildID=Ke6ippcm9Jw5SNCWK4ns/XDo7bVauenGqBCsjFADQ/eaK26APkO_pQEjCuuIsM/wmlt4-ICp1ZZEPNU1MAz, not stripped
```

Running `ldd enpasscli` showed:

```
	linux-vdso.so.1 (0x00007ffd19ff3000)
	libc.musl-x86_64.so.1 => not found
```

I then installed `musl` and retried `./enpasscli`: this time I got the help message.

And running `./enpasscli -vault my-vault -sort list` just works...

**Comment by Kwbmm** [comment]
Ok I see... I didn't actually solved the issue, I've circumvented it.

Compiling the project in the container with `CGO_ENABLED=0 go build` will generate a statically linked binary. Which brings me back to the sqlite3 forgotten import.

**Comment by hazcod** [comment]
Can you re-try release 1.1.1?
https://github.com/hazcod/enpass-cli/releases/tag/v1.1.1

**Comment by Kwbmm** [comment]
Damn.. No luck.. Still same issue.

Could you try with `CGO_ENABLED=1`?

**Comment by hazcod** [comment]
Hmm I'm missing some deps in the goreleaser image https://github.com/hazcod/enpass-cli/runs/1916930046?check_suite_focus=true#step:7:120

**Comment by Kwbmm** [comment]
This matter is quite complicate to answer over night :sweat_smile: 

I found some articles (like this [one](https://medium.com/@diogok/on-golang-static-binaries-cross-compiling-and-plugins-1aed33499671)) which may give some hints.

Many people hint to the fact that you gotta install the right libraries and pick the right compiler for each system if you want to create a static binary.

I need to dig more into this. Might make a fork over the weekend and test on my own

**Comment by Kwbmm** [comment]
I did some work today on my fork and failed a lot, however I think I'm getting clarity on how this project should be cross-compiled.

I found [this link](https://www.yellowduck.be/posts/cross-compile-a-go-package-which-uses-sqlite3/) and I concluded 3 things:

  - `CGO_ENALBED` must be set to `1`
  - We need `musl-cross` package
  - Based on the platform and architecture we're going to compile for, the `CC` flag should be set to a different compiler (provided by `musl-cross`

So I went on and attempted that on my fork on branch `fix/release`. 

1. First of all, I simplified as much as possible the pipeline, so I removed the other workflows I didn't need.
2. Then I decided to remove the docker `goreleaser` version and install it directly on the pipeline machine. This is because the docker version has issues when `CGO_ENABLED=1`, which is what we need here.
3. Then I started to build one thing at a time, excluding OSes and architectures that were problematic for their own reasons (`freebsd` and `darwin + arm64`).
4. I managed to install all the needed deps for `musl-cross` to be compiled successfully. Compiling `musl-cross` is very expensive in terms of time (it takes around 20 minutes).

I still didn't succeed in compiling `enpass-cli` correctly, but I believe it's because I don't know how to tell `goreleaser` to switch compiler based on the architecture and OS it is compiling for.

You can take a look at what I did here and if you have any suggestion on the `goreleaser` part, that'd be great! :)

**Comment by Kwbmm** [comment]
Hello again!

I have done more stuff and I am having a good amount of success. So far, on my test branch I managed to build enpass-cli for linux-amd64, linux-armhf and darwin-amd64.

I have tested both linux versions and they work, but I'm not sure `darwin-amd64` is good. Could you give it a try @hazcod ? It's my understanding that you have a Mac at hand. Link here: https://github.com/Kwbmm/enpass-cli/releases/tag/v1.1.5

----

**For the interested:** I have changed approach and ditched `musl-cross` package in favour of a docker image that handles this (suggested by Goreleaser itself): https://github.com/troian/golang-cross . You can see the works of this in the `fix/release-troian` branch. I believe this approach will successfully build an image for `Windows x64` and `Linux arm64`. However, I've already seen that I'll need some work to build `i386` binaries:
  - `Linux i386`: It's probably just a matter of installing in the image the `gcc-multilib` and  `g++-multilib` packages
  - `Win i386`: will require more investigation

**Comment by hazcod** [comment]
1.2.0 is up! https://github.com/hazcod/enpass-cli/releases/tag/v1.2.0
